resources:
  - frontend.yaml
  - ingress.yaml

configMapGenerator:
  - name: react-frontend-config #fix me
    files:
      - config.json=config/frontend-config.json

generatorOptions:
  disableNameSuffixHash: true