import type { Metadata } from 'next';
import { themeConfig } from '@/lib/theme.config';
import { ThemeProvider, ThemeScript } from '@vapor-ui/core';
import './globals.css';
import '@vapor-ui/core/styles.css';
import StyledComponentsRegistry from '@/providers/StyledComponentsRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        {/* FOUC 방지를 위한 스크립트입니다.
          <head> 태그의 최상단에 위치하는 것을 권장합니다.
        */}
        <ThemeScript config={themeConfig} />
      </head>
      <body>
        {/* 동적 테마 관리를 위한 프로바이더 */}
        <ThemeProvider config={themeConfig}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
