import type { Metadata } from 'next';

import '../styles/font.css';
import '@vapor-ui/core/styles.css';
import StyledComponentsRegistry from '@/providers/StyledComponentsRegistry';
import { GlobalStyle } from '@/styles/globalStyles';
import { LayoutContainer } from '@/components/LayoutContainer';
import { BottomNav } from '@/components/navigation/BottomNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <main>
            <LayoutContainer>
              {children}
            </LayoutContainer>
          </main>
          <BottomNav />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
